
###
POST localhost:8080/customers
Content-Type: application/json

{
  "name": "Oleg",
  "login": "log",
  "password": "password",
  "email": "oleg@oleg.com"
}

###
GET localhost:8080/customers/845808

###
DELETE localhost:8080/customers/845808

###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Морковь",
  "price": 70,
  "amount": 1
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 2,
  "name": "Яблоко",
  "price": 70,
  "amount": 1
}

###
DELETE localhost:8080/products/2

###
GET localhost:8080/products/1

###
GET localhost:8080/products?name=Морковь

###
POST localhost:8080/carts/391441
Content-Type: application/json

{
  "id": 2,
  "amount": 1
}

###
PUT localhost:8080/carts/454547/product/2
Content-Type: application/json

{
  "amount": 3
}

###
DELETE localhost:8080/carts/454547/products/2

###
POST localhost:8080/payment
Content-Type: application/json

{
  "numberCart": "1111",
  "idUser": 391441

}


