###
POST localhost:8080/carts/1
Content-Type: application/json

{
  "id": 4,
  "amount": 1
}

###
GET localhost:8080/carts/1

###
PUT localhost:8080/carts/1/product/1
Content-Type: application/json

{
  "amount": 2
}

###
DELETE localhost:8080/carts/2/products/1