
###
POST localhost:8080/customers
Content-Type: application/json

{
  "name": "Valera",
  "login": "log",
  "password": "password",
  "email": "oleg@oleg.com"
}

###
GET localhost:8080/customers/2

###
DELETE localhost:8080/customers/2

###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Почка",
  "price": 500000,
  "amount": 2
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 6,
  "name": "Почка",
  "price": 700000,
  "amount": 3
}

###
DELETE localhost:8080/products/1

###
GET localhost:8080/products/6

###
GET localhost:8080/products?name=Царь

###
POST localhost:8080/carts/6
Content-Type: application/json

{
  "id": 6,
  "amount": 1
}

###
GET localhost:8080/customers/6

###
PUT localhost:8080/carts/5/product/1
Content-Type: application/json

{
  "amount": 1
}

###
DELETE localhost:8080/carts/5/products/2

###
POST localhost:8080/payment
Content-Type: application/json

{
  "numberCart": "1111",
  "idUser": 6

}


