
###
POST localhost:8080/customers
Content-Type: application/json

{
  "name": "Oleg",
  "login": "log",
  "password": "password",
  "email": "oleg@oleg.com"
}

###
GET localhost:8080/customers/13

###
DELETE localhost:8080/customers/11

###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Царь-Бомба",
  "price": 10000000,
  "amount": 1
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 4,
  "name": "Сода",
  "price": 730,
  "amount": 1
}

###
DELETE localhost:8080/products/2

###
GET localhost:8080/products/5

###
GET localhost:8080/products?name=Царь

###
POST localhost:8080/carts/13
Content-Type: application/json

{
  "id": 5,
  "amount": 2
}

###
PUT localhost:8080/carts/13/product/5
Content-Type: application/json

{
  "amount": 3
}

###
DELETE localhost:8080/carts/12/products/4

###
POST localhost:8080/payment
Content-Type: application/json

{
  "numberCart": "1111",
  "idUser": 9

}


