###
POST localhost:8080/customers
Content-Type: application/json

{
  "name": "Valera",
  "login": "log",
  "password": "password",
  "email": "oleg@oleg.com"
}

###
GET localhost:8080/customers/2

###
DELETE localhost:8080/customers/1