
###
POST localhost:8080/customers
Content-Type: application/json

{
  "name": "Valera",
  "login": "log",
  "password": "password",
  "email": "oleg@oleg.com"
}

###
GET localhost:8080/customers/1

###
DELETE localhost:8080/customers/1

###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Дочка",
  "price": 1000,
  "amount": 50
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 1,
  "name": "Лосось",
  "price": 500000,
  "amount": 2
}

###
DELETE localhost:8080/products/1

###
GET localhost:8080/products/1

###
GET localhost:8080/products?name=ка

###
POST localhost:8080/carts/2
Content-Type: application/json

{
  "id": 2,
  "amount": 1
}

###
GET localhost:8080/customers/2

###
PUT localhost:8080/carts/2/product/2
Content-Type: application/json

{
  "amount": 2
}

###
DELETE localhost:8080/carts/2/products/2

###
POST localhost:8080/promocode
Content-Type: application/json

{
  "promocode": "sale20",
  "percent": 20
}

###
GET localhost:8080/promocode/sale20

###
PUT localhost:8080/promocode/sale15
Content-Type: application/json

{
  "percent": 15
}

###
POST localhost:8080/payment
Content-Type: application/json

{
  "numberCart": "1111",
  "idUser": 2,
  "promoCode": "sale20"

}


